import {
  AlertTriangle,
  ArrowDown,
  ArrowUp,
  AtSign,
  Binary,
  CalendarCheck,
  CalendarClock,
  CalendarPlus,
  CalendarRange,
  Check,
  ChevronDown,
  ChevronRight,
  Clock,
  Clipboard,
  Combine,
  Copy,
  Crop,
  Dices,
  Download,
  Droplets,
  Eraser,
  FileCheck,
  FileCode2,
  FileImage,
  FileKey,
  ContactRound,
  FileSpreadsheet,
  FileText,
  FolderOpen,
  Frame,
  Globe,
  Hash,
  Hexagon,
  History,
  Hourglass,
  Images,
  Info,
  KeyRound,
  Layers,
  LayoutGrid,
  Link,
  ListChecks,
  Loader2,
  Lock,
  Maximize,
  Maximize2,
  Minimize2,
  Minus,
  Monitor,
  Moon,
  Palette,
  Printer,
  PanelLeft,
  Play,
  BookOpen,
  Plus,
  Presentation,
  ReceiptText,
  Repeat,
  ScanText,
  ScrollText,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Save,
  Scissors,
  ServerCrash,
  Settings,
  ShieldCheck,
  Search,
  SquareAsterisk,
  Superscript,
  Sun,
  Table,
  Ticket,
  Timer,
  Trash2,
  Type,
  Wrench,
  X,
  type LucideIcon,
} from 'lucide-react';

const MAP: Record<string, LucideIcon> = {
  merge: Combine,
  compress: Minimize2,
  combine: Combine,
  scissors: Scissors,
  'layout-grid': LayoutGrid,
  'rotate-cw': RotateCw,
  copy: Copy,
  eraser: Eraser,
  droplets: Droplets,
  hash: Hash,
  info: Info,
  minimize: Minimize2,
  images: Images,
  'file-image': FileImage,
  'id-card': ContactRound,
  'file-text': FileText,
  maximize: Maximize,
  maximize2: Maximize2,
  minus: Minus,
  clipboard: Clipboard,
  serverCrash: ServerCrash,
  crop: Crop,
  frame: Frame,
  type: Type,
  wrench: Wrench,
  receipt: ReceiptText,
  word: FileText,
  excel: FileSpreadsheet,
  ppt: Presentation,
  markdown: FileCode2,
  table: Table,
  book: BookOpen,
  scan: ScanText,
  layers: Layers,
  queue: ListChecks,
  settings: Settings,
  search: Search,
  close: X,
  check: Check,
  warning: AlertTriangle,
  spinner: Loader2,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  folder: FolderOpen,
  download: Download,
  save: Save,
  play: Play,
  plus: Plus,
  trash: Trash2,
  up: ArrowUp,
  down: ArrowDown,
  reset: RotateCcw,
  refresh: RefreshCw,
  clock: Clock,
  'calendar-range': CalendarRange,
  'calendar-plus': CalendarPlus,
  'calendar-check': CalendarCheck,
  'calendar-clock': CalendarClock,
  hourglass: Hourglass,
  repeat: Repeat,
  history: History,
  sun: Sun,
  moon: Moon,
  monitor: Monitor,
  palette: Palette,
  sidebar: PanelLeft,
  shield: ShieldCheck,
  printer: Printer,
  globe: Globe,
  file: FileText,
  'file-key': FileKey,
  'file-check': FileCheck,
  binary: Binary,
  superscript: Superscript,
  hexagon: Hexagon,
  link: Link,
  'at-sign': AtSign,
  ticket: Ticket,
  lock: Lock,
  'key-round': KeyRound,
  timer: Timer,
  'scroll-text': ScrollText,
  dices: Dices,
  'square-asterisk': SquareAsterisk,
};

export type IconName = keyof typeof MAP;

export function Icon({
  name,
  size = 16,
  className = '',
  strokeWidth = 1.75,
}: {
  name: string;
  size?: number;
  className?: string;
  strokeWidth?: number;
}) {
  const Component = MAP[name] ?? FileText;
  return <Component size={size} strokeWidth={strokeWidth} className={className} aria-hidden />;
}
