import type { FileKind, ToolCategory, ToolId } from './protocol';
import type { ToolField } from './fields';
import { fieldsOf } from './fields';

export type ToolLayout =
  | 'standard'
  | 'organizer'
  | 'splitter'
  | 'metadata'
  | 'image-grid';

export type ToolWorkflow =
  | 'page-management'
  | 'page-layout'
  | 'annotation'
  | 'conversion'
  | 'extraction'
  | 'optimization'
  | 'metadata'
  | 'image-processing';

export type ToolFormat = FileKind | 'image' | 'jpg' | 'png' | 'webp' | 'tiff';

export interface ToolDescriptor {
  id: ToolId;
  nameKey: string;
  descKey: string;
  category: ToolCategory;
  workflow: ToolWorkflow;
  inputFormats: ToolFormat[];
  outputFormats: ToolFormat[];
  icon: string;
  order: number;
  /** MIME/extension filter accepted by the drop zone and the native picker. */
  accept: string;
  multiFile: boolean;
  layout: ToolLayout;
  fields: ToolField[];
  /** How the result is presented: a list of PDFs, images, or an inline report. */
  artifactKind: FileKind;
  /** Order of the picked files is meaningful to the tool. */
  orderSensitive?: boolean;
  keywords?: string[];
}

export const TOOL_WORKFLOWS: ToolWorkflow[] = [
  'page-management', 'page-layout', 'annotation', 'conversion', 'extraction', 'optimization', 'metadata', 'image-processing',
];

const POSITION_OPTIONS = [
  { value: 'top-left', labelKey: 'layout.topLeft' },
  { value: 'top-center', labelKey: 'layout.topCenter' },
  { value: 'top-right', labelKey: 'layout.topRight' },
  { value: 'middle-left', labelKey: 'layout.middleLeft' },
  { value: 'center', labelKey: 'layout.center' },
  { value: 'middle-right', labelKey: 'layout.middleRight' },
  { value: 'bottom-left', labelKey: 'layout.bottomLeft' },
  { value: 'bottom-center', labelKey: 'layout.bottomCenter' },
  { value: 'bottom-right', labelKey: 'layout.bottomRight' },
];
const POSITION_PRESENTATION = 'position-grid' as const;

const EDGE_PRESETS = [
  { value: 'none', labelKey: 'opt.edgePreset.none', applies: { top: 0, right: 0, bottom: 0, left: 0 } },
  { value: 'tight', labelKey: 'opt.edgePreset.tight', applies: { top: 10, right: 10, bottom: 10, left: 10 } },
  { value: 'normal', labelKey: 'opt.edgePreset.normal', applies: { top: 28, right: 24, bottom: 28, left: 24 } },
  { value: 'wide', labelKey: 'opt.edgePreset.wide', applies: { top: 50, right: 40, bottom: 50, left: 40 } },
];

const PAGES_FIELD: ToolField = { type: 'pageRanges', key: 'pages', labelKey: 'opt.pages', default: 'all' };
const IMAGES_FIELD = (def = true): ToolField => ({
  type: 'boolean',
  key: 'includeImages',
  labelKey: 'opt.convert.includeImages',
  descriptionKey: 'opt.convert.includeImages.hint',
  default: def,
});
const PAGE_BREAK_FIELD: ToolField = {
  type: 'boolean',
  key: 'pageBreaks',
  labelKey: 'opt.convert.pageBreaks',
  default: false,
};
const DPI_FIELD: ToolField = {
  type: 'slider',
  key: 'dpi',
  labelKey: 'opt.images.dpi',
  default: 144,
  min: 72,
  max: 300,
  step: 6,
  unit: 'dpi',
  descriptionKey: 'opt.images.dpi.hint',
  presets: [
    { value: 96, labelKey: 'opt.images.dpi.screen' },
    { value: 150, labelKey: 'opt.images.dpi.standard' },
    { value: 300, labelKey: 'opt.images.dpi.print' },
  ],
};
const DOCX_MIME = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
const DOC_MIME = 'application/msword,.doc';
const XLS_MIME = 'application/vnd.ms-excel,.xls';
const PPT_MIME = 'application/vnd.ms-powerpoint,.ppt';
const XLSX_MIME = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
const PPTX_MIME = 'application/vnd.openxmlformats-officedocument.presentationml.presentation';
const IMAGE_ACCEPT = 'image/jpeg,image/png,image/webp,image/tiff';
const PORTRAIT_IMAGE_ACCEPT = 'image/jpeg,image/png,image/webp';

const imageFields = (tool: 'compress' | 'resize' | 'crop' | 'rotate' | 'convert' | 'info'): ToolField[] => {
  if (tool === 'compress') return [
    { type: 'select', key: 'format', labelKey: 'opt.image.format', default: 'original', options: [
      { value: 'original', labelKey: 'opt.image.original' }, { value: 'jpeg', labelKey: 'opt.image.jpeg' },
      { value: 'png', labelKey: 'opt.image.png' }, { value: 'webp', labelKey: 'opt.image.webp' },
      { value: 'tiff', labelKey: 'opt.image.tiff' },
    ] },
    { type: 'slider', key: 'quality', labelKey: 'opt.image.quality', descriptionKey: 'opt.image.quality.hint', default: 82, min: 20, max: 100, step: 1, unit: 'percent', presets: [
      { value: 55, labelKey: 'opt.image.quality.small' }, { value: 80, labelKey: 'opt.image.quality.standard' }, { value: 95, labelKey: 'opt.image.quality.high' },
    ], showIf: { field: 'format', in: ['jpeg', 'webp', 'tiff'] } },
    { type: 'number', key: 'maxEdge', labelKey: 'opt.image.maxEdge', descriptionKey: 'opt.image.maxEdge.hint', default: 0, min: 0, max: 16000, step: 100, suffixKey: 'unit.px' },
    { type: 'color', key: 'background', labelKey: 'opt.image.background', default: '#ffffff', showIf: { field: 'format', in: ['jpeg'] } },
  ];
  if (tool === 'resize') return [
    { type: 'number', key: 'width', labelKey: 'opt.image.width', default: 1600, min: 1, max: 16000, suffixKey: 'unit.px', row: 'size' },
    { type: 'number', key: 'height', labelKey: 'opt.image.height', default: 1600, min: 1, max: 16000, suffixKey: 'unit.px', row: 'size' },
    { type: 'select', key: 'fit', labelKey: 'opt.image.fit', default: 'inside', options: [
      { value: 'inside', labelKey: 'opt.image.fitInside' }, { value: 'cover', labelKey: 'opt.image.fitCover' },
      { value: 'fill', labelKey: 'opt.image.fitFill' },
    ] },
    { type: 'boolean', key: 'withoutEnlargement', labelKey: 'opt.image.withoutEnlargement', default: true },
  ];
  if (tool === 'crop') return [
    { type: 'select', key: 'aspect', labelKey: 'opt.image.aspect', default: '1:1', options: [
      { value: '1:1', labelKey: 'opt.image.aspect.square' }, { value: '4:3', labelKey: 'opt.image.aspect.landscape' },
      { value: '3:4', labelKey: 'opt.image.aspect.portrait' }, { value: '16:9', labelKey: 'opt.image.aspect.wide' },
      { value: 'original', labelKey: 'opt.image.aspect.original' },
    ] },
    { type: 'select', key: 'position', labelKey: 'opt.image.position', default: 'centre', options: [
      { value: 'centre', labelKey: 'opt.image.position.centre' }, { value: 'north', labelKey: 'opt.image.position.top' },
      { value: 'south', labelKey: 'opt.image.position.bottom' }, { value: 'west', labelKey: 'opt.image.position.left' },
      { value: 'east', labelKey: 'opt.image.position.right' },
    ] },
  ];
  if (tool === 'rotate') return [
    { type: 'select', key: 'angle', labelKey: 'opt.image.angle', default: 90, options: [
      { value: 90, labelKey: 'opt.image.angle.90' }, { value: 180, labelKey: 'opt.image.angle.180' }, { value: 270, labelKey: 'opt.image.angle.270' },
    ] },
    { type: 'boolean', key: 'flipHorizontal', labelKey: 'opt.image.flipHorizontal', default: false },
    { type: 'boolean', key: 'flipVertical', labelKey: 'opt.image.flipVertical', default: false },
  ];
  if (tool === 'convert') return [
    { type: 'select', key: 'format', labelKey: 'opt.image.format', default: 'webp', options: [
      { value: 'jpeg', labelKey: 'opt.image.jpeg' }, { value: 'png', labelKey: 'opt.image.png' },
      { value: 'webp', labelKey: 'opt.image.webp' },
      { value: 'tiff', labelKey: 'opt.image.tiff' },
    ] },
    { type: 'slider', key: 'quality', labelKey: 'opt.image.quality', descriptionKey: 'opt.image.quality.hint', default: 85, min: 20, max: 100, step: 1, unit: 'percent', presets: [
      { value: 55, labelKey: 'opt.image.quality.small' }, { value: 80, labelKey: 'opt.image.quality.standard' }, { value: 95, labelKey: 'opt.image.quality.high' },
    ] },
    { type: 'color', key: 'background', labelKey: 'opt.image.background', default: '#ffffff', showIf: { field: 'format', in: ['jpeg'] } },
  ];
  return [];
};

const imageCutoutFields: ToolField[] = [
  { type: 'boolean', key: 'transparent', labelKey: 'opt.cutout.transparent', descriptionKey: 'opt.cutout.transparent.hint', default: true },
  { type: 'color', key: 'background', labelKey: 'opt.cutout.background', default: '#ffffff', showIf: { field: 'transparent', in: [false] } },
];

const idPhotoFields: ToolField[] = [
  { type: 'select', key: 'size', labelKey: 'opt.idPhoto.size', default: 'one-inch', presentation: 'cards', options: [
    { value: 'one-inch', labelKey: 'opt.idPhoto.oneInch', descriptionKey: 'opt.idPhoto.oneInch.hint' },
    { value: 'two-inch', labelKey: 'opt.idPhoto.twoInch', descriptionKey: 'opt.idPhoto.twoInch.hint' },
  ] },
  { type: 'color', key: 'background', labelKey: 'opt.idPhoto.background', default: '#438edb' },
  { type: 'slider', key: 'maxFileKb', labelKey: 'opt.idPhoto.maxFileKb', descriptionKey: 'opt.idPhoto.maxFileKb.hint', default: 100, min: 10, max: 1000, step: 1, unit: 'kb', presets: [
    { value: 50, labelKey: 'opt.idPhoto.limit50' }, { value: 100, labelKey: 'opt.idPhoto.limit100' },
    { value: 200, labelKey: 'opt.idPhoto.limit200' }, { value: 500, labelKey: 'opt.idPhoto.limit500' },
  ] },
  { type: 'slider', key: 'scale', labelKey: 'opt.idPhoto.scale', descriptionKey: 'opt.idPhoto.scale.hint', default: 100, min: 70, max: 130, step: 1, unit: 'percent' },
  { type: 'slider', key: 'verticalOffset', labelKey: 'opt.idPhoto.verticalOffset', descriptionKey: 'opt.idPhoto.verticalOffset.hint', default: 0, min: -20, max: 20, step: 1, unit: 'percent' },
  { type: 'boolean', key: 'printSheet', labelKey: 'opt.idPhoto.printSheet', descriptionKey: 'opt.idPhoto.printSheet.hint', default: true },
];

const imagePrintFields: ToolField[] = [
  { type: 'select', key: 'paper', labelKey: 'opt.imagePrint.paper', default: 'a4', options: [
    { value: 'a4', labelKey: 'opt.imagePrint.a4' }, { value: 'letter', labelKey: 'opt.imagePrint.letter' },
  ] },
  { type: 'select', key: 'orientation', labelKey: 'opt.imagePrint.orientation', default: 'auto', options: [
    { value: 'auto', labelKey: 'opt.imagePrint.auto' }, { value: 'portrait', labelKey: 'opt.imagePrint.portrait' }, { value: 'landscape', labelKey: 'opt.imagePrint.landscape' },
  ] },
  { type: 'number', key: 'marginMm', labelKey: 'opt.imagePrint.margin', default: 10, min: 0, max: 40, step: 1, suffixKey: 'unit.mm' },
  { type: 'select', key: 'fit', labelKey: 'opt.imagePrint.fit', default: 'contain', options: [
    { value: 'contain', labelKey: 'opt.imagePrint.contain' }, { value: 'cover', labelKey: 'opt.imagePrint.cover' },
  ] },
];

type ToolDefinition = Omit<ToolDescriptor, 'workflow' | 'inputFormats' | 'outputFormats'>;

const TOOL_DEFINITIONS: ToolDefinition[] = [
  {
    id: 'merge',
    nameKey: 'tool.merge.name',
    descKey: 'tool.merge.desc',
    category: 'organize',
    icon: 'merge',
    order: 10,
    accept: 'application/pdf',
    multiFile: true,
    layout: 'standard',
    artifactKind: 'pdf',
    orderSensitive: true,
    keywords: ['合并', 'merge', 'hebing'],
    fields: [
      {
        type: 'select',
        key: 'pageSize',
        labelKey: 'opt.pageSize',
        descriptionKey: 'opt.pageSize.hint',
        default: 'keep',
        section: 'layout',
        row: 'a',
        options: [
          { value: 'keep', labelKey: 'opt.pageSize.keep' },
          { value: 'match-first', labelKey: 'opt.pageSize.matchFirst' },
          { value: 'a4', labelKey: 'opt.pageSize.a4' },
          { value: 'letter', labelKey: 'opt.pageSize.letter' },
        ],
      },
      {
        type: 'select',
        key: 'orientation',
        labelKey: 'opt.orientation',
        default: 'keep',
        section: 'layout',
        row: 'a',
        options: [
          { value: 'keep', labelKey: 'opt.orientation.keep' },
          { value: 'portrait', labelKey: 'opt.orientation.portrait' },
          { value: 'landscape', labelKey: 'opt.orientation.landscape' },
        ],
      },
      {
        type: 'number',
        key: 'margin',
        labelKey: 'opt.margin',
        default: 0,
        min: 0,
        max: 72,
        step: 1,
        suffixKey: 'unit.pt',
        displayUnit: 'mm',
        section: 'layout',
        row: 'b',
      },
    ],
  },
  {
    id: 'split',
    nameKey: 'tool.split.name',
    descKey: 'tool.split.desc',
    category: 'organize',
    icon: 'scissors',
    order: 20,
    accept: 'application/pdf',
    multiFile: false,
    layout: 'splitter',
    artifactKind: 'pdf',
    keywords: ['拆分', 'split', 'chaifen'],
    fields: [
      {
        type: 'select',
        key: 'mode',
        labelKey: 'opt.split.mode',
        descriptionKey: 'opt.split.mode.hint',
        default: 'each-page',
        presentation: 'cards',
        options: [
          { value: 'each-page', labelKey: 'opt.split.mode.each', descriptionKey: 'opt.split.mode.each.hint' },
          { value: 'every-n', labelKey: 'opt.split.mode.everyN', descriptionKey: 'opt.split.mode.everyN.hint' },
          { value: 'ranges', labelKey: 'opt.split.mode.ranges', descriptionKey: 'opt.split.mode.ranges.hint' },
          { value: 'halves', labelKey: 'opt.split.mode.halves', descriptionKey: 'opt.split.mode.halves.hint' },
          { value: 'manual', labelKey: 'opt.split.mode.manual', descriptionKey: 'opt.split.mode.manual.hint' },
        ],
      },
      {
        type: 'number',
        key: 'everyN',
        labelKey: 'opt.split.everyN',
        default: 2,
        min: 1,
        max: 500,
        step: 1,
        showIf: { field: 'mode', in: ['every-n'] },
      },
      {
        type: 'pageRanges',
        key: 'ranges',
        labelKey: 'opt.ranges',
        default: '1-3,4',
        showIf: { field: 'mode', in: ['ranges'] },
      },
      {
        type: 'boolean',
        key: 'rangesAsOne',
        labelKey: 'opt.split.rangesAsOne',
        default: false,
        showIf: { field: 'mode', in: ['ranges'] },
      },
    ],
  },
  {
    id: 'organize',
    nameKey: 'tool.organize.name',
    descKey: 'tool.organize.desc',
    category: 'organize',
    icon: 'layout-grid',
    order: 30,
    accept: 'application/pdf',
    multiFile: true,
    layout: 'organizer',
    artifactKind: 'pdf',
    orderSensitive: true,
    keywords: ['组织', '页面', 'organize', '排序'],
    fields: [
      {
        type: 'select',
        key: 'pageSize',
        labelKey: 'opt.pageSize',
        default: 'keep',
        section: 'layout',
        options: [
          { value: 'keep', labelKey: 'opt.pageSize.keep' },
          { value: 'match-first', labelKey: 'opt.pageSize.matchFirst' },
          { value: 'a4', labelKey: 'opt.pageSize.a4' },
        ],
      },
    ],
  },
  {
    id: 'rotate',
    nameKey: 'tool.rotate.name',
    descKey: 'tool.rotate.desc',
    category: 'organize',
    icon: 'rotate-cw',
    order: 40,
    accept: 'application/pdf',
    multiFile: true,
    layout: 'standard',
    artifactKind: 'pdf',
    keywords: ['旋转', 'rotate'],
    fields: [
      {
        type: 'select',
        key: 'angle',
        labelKey: 'opt.rotate.angle',
        default: 90,
        row: 'a',
        options: [
          { value: 90, labelKey: 'opt.rotate.clockwise' },
          { value: -90, labelKey: 'opt.rotate.counterclockwise' },
          { value: 180, labelKey: 'opt.rotate.upsideDown' },
        ],
      },
      {
        type: 'pageRanges',
        key: 'pages',
        labelKey: 'opt.pages',
        default: 'all',
        row: 'b',
      },
    ],
  },
  {
    id: 'extract-pages',
    nameKey: 'tool.extract.name',
    descKey: 'tool.extract.desc',
    category: 'organize',
    icon: 'copy',
    order: 50,
    accept: 'application/pdf',
    multiFile: true,
    layout: 'standard',
    artifactKind: 'pdf',
    keywords: ['提取', 'extract'],
    fields: [
      { type: 'pageRanges', key: 'pages', labelKey: 'opt.pages', default: '1' },
      {
        type: 'boolean',
        key: 'oneFilePerGroup',
        labelKey: 'opt.extract.onePerRange',
        default: false,
      },
    ],
  },
  {
    id: 'delete-pages',
    nameKey: 'tool.delete.name',
    descKey: 'tool.delete.desc',
    category: 'organize',
    icon: 'eraser',
    order: 60,
    accept: 'application/pdf',
    multiFile: true,
    layout: 'standard',
    artifactKind: 'pdf',
    keywords: ['删除', 'delete'],
    fields: [
      {
        type: 'pageRanges',
        key: 'pages',
        labelKey: 'opt.pages',
        descriptionKey: 'opt.deletePages.hint',
        placeholderKey: 'opt.deletePages.placeholder',
        default: '',
        allowEmpty: false,
        allowAll: false,
      },
    ],
  },
  {
    id: 'watermark',
    nameKey: 'tool.watermark.name',
    descKey: 'tool.watermark.desc',
    category: 'edit',
    icon: 'droplets',
    order: 70,
    accept: 'application/pdf',
    multiFile: true,
    layout: 'standard',
    artifactKind: 'pdf',
    keywords: ['水印', 'watermark'],
    fields: [
      {
        type: 'text',
        key: 'text',
        labelKey: 'opt.watermark.text',
        default: '机密文件',
        maxLength: 120,
        required: true,
      },
      {
        type: 'select',
        key: 'position',
        labelKey: 'opt.position',
        default: 'center',
        options: POSITION_OPTIONS,
        presentation: POSITION_PRESENTATION,
        section: 'layout',
      },
      {
        type: 'slider',
        key: 'fontSize',
        labelKey: 'opt.fontSize',
        default: 48,
        min: 8,
        max: 200,
        step: 1,
        unit: 'pt',
        row: 'c',
      },
      {
        type: 'slider',
        key: 'opacity',
        labelKey: 'opt.opacity',
        default: 22,
        min: 3,
        max: 100,
        step: 1,
        unit: 'percent',
        row: 'c',
      },
      {
        type: 'slider',
        key: 'rotation',
        labelKey: 'opt.rotation',
        default: 45,
        min: -90,
        max: 90,
        step: 5,
        unit: 'deg',
        row: 'd',
      },
      {
        type: 'color',
        key: 'color',
        labelKey: 'opt.color',
        default: '#6b7280',
        row: 'd',
      },
      {
        type: 'slider',
        key: 'tileGap',
        labelKey: 'opt.watermark.tileGap',
        descriptionKey: 'opt.watermark.tileGap.hint',
        default: 60,
        min: 10,
        max: 300,
        step: 5,
        unit: 'pt',
        showIf: { field: 'position', in: ['center'] },
        section: 'advanced',
      },
      {
        type: 'boolean',
        key: 'tiled',
        labelKey: 'opt.watermark.tiled',
        default: false,
        section: 'advanced',
      },
      {
        type: 'select',
        key: 'layer',
        labelKey: 'opt.watermark.layer',
        default: 'above',
        section: 'advanced',
        options: [
          { value: 'above', labelKey: 'opt.watermark.layerAbove' },
          { value: 'below', labelKey: 'opt.watermark.layerBelow' },
        ],
      },
      { type: 'pageRanges', key: 'pages', labelKey: 'opt.pages', default: 'all', section: 'advanced' },
    ],
  },
  {
    id: 'page-numbers',
    nameKey: 'tool.pageNumbers.name',
    descKey: 'tool.pageNumbers.desc',
    category: 'edit',
    icon: 'hash',
    order: 80,
    accept: 'application/pdf',
    multiFile: true,
    layout: 'standard',
    artifactKind: 'pdf',
    keywords: ['页码', 'number'],
    fields: [
      {
        type: 'select',
        key: 'position',
        labelKey: 'opt.position',
        default: 'bottom-center',
        options: POSITION_OPTIONS,
        presentation: POSITION_PRESENTATION,
        section: 'layout',
        row: 'a',
      },
      {
        type: 'text',
        key: 'format',
        labelKey: 'opt.pageNumbers.format',
        descriptionKey: 'opt.pageNumbers.format.hint',
        default: '{n} / {total}',
        maxLength: 40,
        row: 'a',
      },
      {
        type: 'number',
        key: 'start',
        labelKey: 'opt.pageNumbers.start',
        default: 1,
        min: 0,
        max: 9999,
        section: 'layout',
        row: 'b',
      },
      {
        type: 'number',
        key: 'margin',
        labelKey: 'opt.margin',
        default: 24,
        min: 4,
        max: 120,
        suffixKey: 'unit.mm',
        displayUnit: 'mm',
        section: 'layout',
        row: 'b',
      },
      {
        type: 'slider',
        key: 'fontSize',
        labelKey: 'opt.fontSize',
        default: 11,
        min: 6,
        max: 48,
        step: 1,
        unit: 'pt',
        row: 'c',
      },
      { type: 'color', key: 'color', labelKey: 'opt.color', default: '#111827', row: 'c' },
      {
        type: 'boolean',
        key: 'skipFirst',
        labelKey: 'opt.pageNumbers.skipFirst',
        default: false,
        section: 'advanced',
      },
      { type: 'pageRanges', key: 'pages', labelKey: 'opt.pages', default: 'all', section: 'advanced' },
    ],
  },
  {
    id: 'metadata',
    nameKey: 'tool.metadata.name',
    descKey: 'tool.metadata.desc',
    category: 'metadata',
    icon: 'info',
    order: 90,
    accept: 'application/pdf',
    multiFile: true,
    layout: 'metadata',
    artifactKind: 'pdf',
    keywords: ['元数据', '属性', 'metadata'],
    fields: [
      {
        type: 'select',
        key: 'mode',
        labelKey: 'opt.metadata.mode',
        default: 'write',
        options: [
          { value: 'read', labelKey: 'opt.metadata.mode.read' },
          { value: 'write', labelKey: 'opt.metadata.mode.write' },
          { value: 'clear', labelKey: 'opt.metadata.mode.clear' },
        ],
      },
      { type: 'text', key: 'title', labelKey: 'opt.metadata.title', default: '', showIf: { field: 'mode', in: ['write'] } },
      { type: 'text', key: 'author', labelKey: 'opt.metadata.author', default: '', showIf: { field: 'mode', in: ['write'] } },
      { type: 'text', key: 'subject', labelKey: 'opt.metadata.subject', default: '', showIf: { field: 'mode', in: ['write'] } },
      { type: 'text', key: 'keywords', labelKey: 'opt.metadata.keywords', default: '', showIf: { field: 'mode', in: ['write'] } },
      { type: 'text', key: 'creator', labelKey: 'opt.metadata.creator', default: '', showIf: { field: 'mode', in: ['write'] } },
      { type: 'text', key: 'producer', labelKey: 'opt.metadata.producer', default: '', showIf: { field: 'mode', in: ['write'] } },
      {
        type: 'boolean',
        key: 'stripXmp',
        labelKey: 'opt.metadata.stripXmp',
        default: true,
        section: 'advanced',
      },
    ],
  },
  {
    id: 'compress',
    nameKey: 'tool.compress.name',
    descKey: 'tool.compress.desc',
    category: 'optimize',
    icon: 'minimize',
    order: 100,
    accept: 'application/pdf',
    multiFile: true,
    layout: 'standard',
    artifactKind: 'pdf',
    keywords: ['压缩', 'optimize', 'compress'],
    fields: [
      {
        type: 'select',
        key: 'preset',
        labelKey: 'opt.compress.preset',
        default: 'balanced',
        uiOnly: true,
        options: [
          { value: 'extreme', labelKey: 'opt.compress.extreme', applies: { imageQuality: 45, maxDpi: 96 } },
          { value: 'balanced', labelKey: 'opt.compress.balanced', applies: { imageQuality: 70, maxDpi: 150 } },
          { value: 'quality', labelKey: 'opt.compress.quality', applies: { imageQuality: 88, maxDpi: 220 } },
        ],
      },
      {
        type: 'slider',
        key: 'imageQuality',
        labelKey: 'opt.compress.imageQuality',
        default: 70,
        min: 20,
        max: 96,
        step: 1,
        unit: 'percent',
        row: 'q',
      },
      {
        type: 'slider',
        key: 'maxDpi',
        labelKey: 'opt.compress.maxDpi',
        default: 150,
        min: 72,
        max: 300,
        step: 6,
        unit: 'dpi',
        row: 'q',
      },
      {
        type: 'boolean',
        key: 'resampleImages',
        labelKey: 'opt.compress.resample',
        default: true,
        section: 'advanced',
      },
      {
        type: 'boolean',
        key: 'objectStreams',
        labelKey: 'opt.compress.objectStreams',
        default: true,
        section: 'advanced',
      },
      {
        type: 'boolean',
        key: 'stripMetadata',
        labelKey: 'opt.compress.stripMetadata',
        default: false,
        section: 'advanced',
      },
    ],
  },
  {
    id: 'pdf-to-images',
    nameKey: 'tool.pdfToImages.name',
    descKey: 'tool.pdfToImages.desc',
    category: 'convert',
    icon: 'images',
    order: 110,
    accept: 'application/pdf',
    multiFile: true,
    layout: 'image-grid',
    artifactKind: 'image',
    keywords: ['转图片', 'png', 'jpg'],
    fields: [
      {
        type: 'select',
        key: 'format',
        labelKey: 'opt.images.format',
        default: 'jpeg',
        row: 'a',
        options: [
          { value: 'jpeg', labelKey: 'opt.images.jpeg' },
          { value: 'png', labelKey: 'opt.images.png' },
          { value: 'webp', labelKey: 'opt.images.webp' },
        ],
      },
      {
        type: 'slider',
        key: 'dpi',
        labelKey: 'opt.images.dpi',
        default: 150,
        min: 72,
        max: 600,
        step: 6,
        unit: 'dpi',
        presets: [
          { value: 96, labelKey: 'opt.images.dpi.screen' },
          { value: 150, labelKey: 'opt.images.dpi.standard' },
          { value: 300, labelKey: 'opt.images.dpi.print' },
        ],
        row: 'a',
      },
      {
        type: 'slider',
        key: 'quality',
        labelKey: 'opt.images.quality',
        default: 88,
        min: 30,
        max: 100,
        step: 1,
        unit: 'percent',
        presets: [
          { value: 60, labelKey: 'opt.image.quality.small' },
          { value: 85, labelKey: 'opt.image.quality.standard' },
          { value: 95, labelKey: 'opt.image.quality.high' },
        ],
        showIf: { field: 'format', in: ['jpeg', 'webp'] },
      },
      {
        type: 'boolean',
        key: 'transparentBackground',
        labelKey: 'opt.images.transparent',
        default: false,
        showIf: { field: 'format', in: ['png', 'webp'] },
      },
      { type: 'pageRanges', key: 'pages', labelKey: 'opt.pages', default: 'all' },
    ],
  },
  {
    id: 'images-to-pdf',
    nameKey: 'tool.imagesToPdf.name',
    descKey: 'tool.imagesToPdf.desc',
    category: 'convert',
    icon: 'file-image',
    order: 120,
    accept: 'image/*',
    multiFile: true,
    layout: 'standard',
    artifactKind: 'pdf',
    orderSensitive: true,
    keywords: ['图片转 pdf', 'jpg to pdf'],
    fields: [
      {
        type: 'select',
        key: 'pageSize',
        labelKey: 'opt.pageSize',
        default: 'auto',
        row: 'a',
        options: [
          { value: 'auto', labelKey: 'opt.pageSize.auto' },
          { value: 'a4', labelKey: 'opt.pageSize.a4' },
          { value: 'letter', labelKey: 'opt.pageSize.letter' },
        ],
      },
      {
        type: 'select',
        key: 'orientation',
        labelKey: 'opt.orientation',
        default: 'auto',
        row: 'a',
        options: [
          { value: 'auto', labelKey: 'opt.orientation.auto' },
          { value: 'portrait', labelKey: 'opt.orientation.portrait' },
          { value: 'landscape', labelKey: 'opt.orientation.landscape' },
        ],
      },
      {
        type: 'select',
        key: 'fit',
        labelKey: 'opt.images.fit',
        default: 'contain',
        row: 'b',
        options: [
          { value: 'contain', labelKey: 'opt.images.fitContain' },
          { value: 'cover', labelKey: 'opt.images.fitCover' },
          { value: 'actual', labelKey: 'opt.images.fitActual' },
        ],
      },
      {
        type: 'slider',
        key: 'margin',
        labelKey: 'opt.margin',
        default: 0,
        min: 0,
        max: 72,
        step: 1,
        unit: 'pt',
        displayUnit: 'mm',
        row: 'b',
      },
      { type: 'color', key: 'background', labelKey: 'opt.images.background', default: '#ffffff' },
      {
        type: 'slider',
        key: 'imageQuality',
        labelKey: 'opt.compress.imageQuality',
        default: 85,
        min: 40,
        max: 100,
        step: 1,
        unit: 'percent',
        section: 'advanced',
      },
    ],
  },
  {
    id: 'resize',
    nameKey: 'tool.resize.name',
    descKey: 'tool.resize.desc',
    category: 'organize',
    icon: 'maximize',
    order: 65,
    accept: 'application/pdf',
    multiFile: true,
    layout: 'standard',
    artifactKind: 'pdf',
    keywords: ['尺寸', '缩放', 'resize', 'a4'],
    fields: [
      {
        type: 'select',
        key: 'target',
        labelKey: 'opt.resize.target',
        default: 'a4',
        row: 'a',
        options: [
          { value: 'a4', labelKey: 'opt.pageSize.a4' },
          { value: 'a5', labelKey: 'opt.pageSize.a5' },
          { value: 'letter', labelKey: 'opt.pageSize.letter' },
          { value: 'match-first', labelKey: 'opt.pageSize.matchFirst' },
          { value: 'scale', labelKey: 'opt.resize.byScale' },
        ],
      },
      {
        type: 'slider',
        key: 'scale',
        labelKey: 'opt.resize.scale',
        default: 100,
        min: 25,
        max: 400,
        step: 5,
        unit: 'percent',
        showIf: { field: 'target', in: ['scale'] },
      },
      {
        type: 'select',
        key: 'orientation',
        labelKey: 'opt.orientation',
        default: 'keep',
        row: 'a',
        options: [
          { value: 'keep', labelKey: 'opt.orientation.keep' },
          { value: 'portrait', labelKey: 'opt.orientation.portrait' },
          { value: 'landscape', labelKey: 'opt.orientation.landscape' },
        ],
      },
      {
        type: 'number',
        key: 'margin',
        labelKey: 'opt.margin',
        default: 0,
        min: 0,
        max: 72,
        suffixKey: 'unit.pt',
        displayUnit: 'mm',
        row: 'b',
      },
      {
        type: 'boolean',
        key: 'keepRatio',
        labelKey: 'opt.resize.keepRatio',
        descriptionKey: 'opt.resize.keepRatio.hint',
        default: true,
        section: 'advanced',
      },
    ],
  },
  {
    id: 'crop',
    nameKey: 'tool.crop.name',
    descKey: 'tool.crop.desc',
    category: 'organize',
    icon: 'crop',
    order: 66,
    accept: 'application/pdf',
    multiFile: true,
    layout: 'standard',
    artifactKind: 'pdf',
    keywords: ['裁剪', 'crop', '切边'],
    fields: [
      {
        type: 'select',
        key: 'edgePreset',
        labelKey: 'opt.edgePreset',
        default: 'none',
        uiOnly: true,
        options: EDGE_PRESETS,
      },
      { type: 'number', key: 'top', labelKey: 'opt.edge.top', default: 0, min: 0, max: 400, suffixKey: 'unit.mm', displayUnit: 'mm', row: 'e1' },
      { type: 'number', key: 'bottom', labelKey: 'opt.edge.bottom', default: 0, min: 0, max: 400, suffixKey: 'unit.mm', displayUnit: 'mm', row: 'e1' },
      { type: 'number', key: 'left', labelKey: 'opt.edge.left', default: 0, min: 0, max: 400, suffixKey: 'unit.mm', displayUnit: 'mm', row: 'e2' },
      { type: 'number', key: 'right', labelKey: 'opt.edge.right', default: 0, min: 0, max: 400, suffixKey: 'unit.mm', displayUnit: 'mm', row: 'e2' },
      {
        type: 'boolean',
        key: 'shrinkToContent',
        labelKey: 'opt.crop.shrink',
        descriptionKey: 'opt.crop.shrink.hint',
        default: false,
        section: 'advanced',
      },
      { type: 'pageRanges', key: 'pages', labelKey: 'opt.pages', default: 'all', section: 'advanced' },
    ],
  },
  {
    id: 'margins',
    nameKey: 'tool.margins.name',
    descKey: 'tool.margins.desc',
    category: 'organize',
    icon: 'frame',
    order: 67,
    accept: 'application/pdf',
    multiFile: true,
    layout: 'standard',
    artifactKind: 'pdf',
    keywords: ['页边距', '白边', 'margin'],
    fields: [
      {
        type: 'slider',
        key: 'edge',
        labelKey: 'opt.margins.edge',
        default: 24,
        min: 0,
        max: 160,
        step: 2,
        unit: 'pt',
        displayUnit: 'mm',
        row: 'm1',
      },
      {
        type: 'select',
        key: 'sides',
        labelKey: 'opt.margins.sides',
        default: 'all',
        row: 'm1',
        options: [
          { value: 'all', labelKey: 'opt.margins.all' },
          { value: 'vertical', labelKey: 'opt.margins.vertical' },
          { value: 'horizontal', labelKey: 'opt.margins.horizontal' },
        ],
      },
      {
        type: 'boolean',
        key: 'keepPageSize',
        labelKey: 'opt.margins.keepSize',
        descriptionKey: 'opt.margins.keepSize.hint',
        default: true,
      },
    ],
  },
  {
    id: 'nup',
    nameKey: 'tool.nup.name',
    descKey: 'tool.nup.desc',
    category: 'organize',
    icon: 'layout-grid',
    order: 68,
    accept: 'application/pdf',
    multiFile: false,
    layout: 'standard',
    artifactKind: 'pdf',
    keywords: ['拼版', 'n-up', '多页合一', '小册子'],
    fields: [
      {
        type: 'select',
        key: 'perSheet',
        labelKey: 'opt.nup.perSheet',
        default: 2,
        row: 'n1',
        options: [
          { value: 2, labelKey: 'opt.nup.two' },
          { value: 4, labelKey: 'opt.nup.four' },
          { value: 6, labelKey: 'opt.nup.six' },
          { value: 9, labelKey: 'opt.nup.nine' },
        ],
      },
      {
        type: 'select',
        key: 'pageSize',
        labelKey: 'opt.pageSize',
        default: 'a4',
        row: 'n1',
        options: [
          { value: 'a4', labelKey: 'opt.pageSize.a4' },
          { value: 'letter', labelKey: 'opt.pageSize.letter' },
          { value: 'match-first', labelKey: 'opt.pageSize.matchFirst' },
        ],
      },
      {
        type: 'select',
        key: 'order',
        labelKey: 'opt.nup.order',
        default: 'horizontal',
        row: 'n2',
        options: [
          { value: 'horizontal', labelKey: 'opt.nup.orderHorizontal' },
          { value: 'vertical', labelKey: 'opt.nup.orderVertical' },
        ],
      },
      {
        type: 'select',
        key: 'orientation',
        labelKey: 'opt.orientation',
        default: 'auto',
        row: 'n2',
        options: [
          { value: 'auto', labelKey: 'opt.orientation.auto' },
          { value: 'portrait', labelKey: 'opt.orientation.portrait' },
          { value: 'landscape', labelKey: 'opt.orientation.landscape' },
        ],
      },
      { type: 'number', key: 'gap', labelKey: 'opt.nup.gap', default: 8, min: 0, max: 60, suffixKey: 'unit.mm', displayUnit: 'mm', row: 'n3' },
      { type: 'number', key: 'margin', labelKey: 'opt.margin', default: 12, min: 0, max: 60, suffixKey: 'unit.mm', displayUnit: 'mm', row: 'n3' },
      { type: 'boolean', key: 'border', labelKey: 'opt.nup.border', default: false, section: 'advanced' },
    ],
  },
  {
    id: 'header-footer',
    nameKey: 'tool.headerFooter.name',
    descKey: 'tool.headerFooter.desc',
    category: 'edit',
    icon: 'type',
    order: 85,
    accept: 'application/pdf',
    multiFile: true,
    layout: 'standard',
    artifactKind: 'pdf',
    keywords: ['页眉', '页脚', 'header', 'footer'],
    fields: [
      { type: 'text', key: 'header', labelKey: 'opt.header.text', default: '', maxLength: 120, placeholderKey: 'opt.text.optional' },
      { type: 'text', key: 'footer', labelKey: 'opt.footer.text', default: '{n} / {total}', maxLength: 120 },
      {
        type: 'select',
        key: 'headerAlign',
        labelKey: 'opt.text.align',
        default: 'center',
        row: 'h1',
        options: [
          { value: 'left', labelKey: 'opt.align.left' },
          { value: 'center', labelKey: 'opt.align.center' },
          { value: 'right', labelKey: 'opt.align.right' },
        ],
      },
      {
        type: 'select',
        key: 'footerAlign',
        labelKey: 'opt.text.align',
        default: 'center',
        row: 'h1',
        options: [
          { value: 'left', labelKey: 'opt.align.left' },
          { value: 'center', labelKey: 'opt.align.center' },
          { value: 'right', labelKey: 'opt.align.right' },
        ],
      },
      { type: 'slider', key: 'fontSize', labelKey: 'opt.fontSize', default: 10, min: 6, max: 28, step: 1, unit: 'pt', row: 'h2' },
      { type: 'number', key: 'margin', labelKey: 'opt.margin', default: 24, min: 6, max: 90, suffixKey: 'unit.mm', displayUnit: 'mm', row: 'h2' },
      { type: 'color', key: 'color', labelKey: 'opt.color', default: '#374151' },
      { type: 'boolean', key: 'skipFirst', labelKey: 'opt.pageNumbers.skipFirst', default: false, section: 'advanced' },
      { type: 'pageRanges', key: 'pages', labelKey: 'opt.pages', default: 'all', section: 'advanced' },
    ],
  },
  {
    id: 'remove-blank',
    nameKey: 'tool.removeBlank.name',
    descKey: 'tool.removeBlank.desc',
    category: 'optimize',
    icon: 'eraser',
    order: 95,
    accept: 'application/pdf',
    multiFile: true,
    layout: 'standard',
    artifactKind: 'pdf',
    keywords: ['空白页', 'blank', '删除空页'],
    fields: [
      {
        type: 'slider',
        key: 'tolerance',
        labelKey: 'opt.blank.tolerance',
        descriptionKey: 'opt.blank.tolerance.hint',
        default: 2,
        min: 0,
        max: 20,
        step: 1,
        unit: 'percent',
      },
      {
        type: 'boolean',
        key: 'reportOnly',
        labelKey: 'opt.blank.reportOnly',
        descriptionKey: 'opt.blank.reportOnly.hint',
        default: false,
      },
    ],
  },
  {
    id: 'repair',
    nameKey: 'tool.repair.name',
    descKey: 'tool.repair.desc',
    category: 'optimize',
    icon: 'wrench',
    order: 105,
    accept: 'application/pdf',
    multiFile: true,
    layout: 'standard',
    artifactKind: 'pdf',
    keywords: ['修复', 'repair', '损坏'],
    fields: [
      { type: 'boolean', key: 'recompress', labelKey: 'opt.repair.recompress', default: true },
      { type: 'boolean', key: 'stripMetadata', labelKey: 'opt.compress.stripMetadata', default: false, section: 'advanced' },
    ],
  },
  {
    id: 'extract-images',
    nameKey: 'tool.extractImages.name',
    descKey: 'tool.extractImages.desc',
    category: 'extract',
    icon: 'images',
    order: 115,
    accept: 'application/pdf',
    multiFile: true,
    layout: 'image-grid',
    artifactKind: 'image',
    keywords: ['提取图片', '图片导出'],
    fields: [
      {
        type: 'select',
        key: 'format',
        labelKey: 'opt.images.format',
        default: 'original',
        row: 'x1',
        options: [
          { value: 'original', labelKey: 'opt.extract.original' },
          { value: 'jpeg', labelKey: 'opt.images.jpeg' },
          { value: 'png', labelKey: 'opt.images.png' },
          { value: 'webp', labelKey: 'opt.images.webp' },
        ],
      },
      {
        type: 'slider',
        key: 'minBytes',
        labelKey: 'opt.extract.minSize',
        descriptionKey: 'opt.extract.minSize.hint',
        default: 10,
        min: 0,
        max: 500,
        step: 10,
        unit: 'kb',
        row: 'x1',
      },
      { type: 'pageRanges', key: 'pages', labelKey: 'opt.pages', default: 'all', section: 'advanced' },
    ],
  },
  {
    id: 'extract-text',
    nameKey: 'tool.extractText.name',
    descKey: 'tool.extractText.desc',
    category: 'extract',
    icon: 'file-text',
    order: 116,
    accept: 'application/pdf',
    multiFile: true,
    layout: 'standard',
    artifactKind: 'json',
    keywords: ['提取文字', '文本', 'ocr 替代'],
    fields: [
      {
        type: 'select',
        key: 'granularity',
        labelKey: 'opt.extract.granularity',
        default: 'single',
        options: [
          { value: 'single', labelKey: 'opt.extract.singleFile' },
          { value: 'per-page', labelKey: 'opt.extract.perPage' },
        ],
      },
      { type: 'boolean', key: 'pageMarkers', labelKey: 'opt.extract.pageMarkers', descriptionKey: 'opt.extract.pageMarkers.hint', default: true },
      { type: 'pageRanges', key: 'pages', labelKey: 'opt.pages', default: 'all', section: 'advanced' },
    ],
  },
  {
    id: 'invoice-merge',
    nameKey: 'tool.invoiceMerge.name',
    descKey: 'tool.invoiceMerge.desc',
    category: 'organize',
    icon: 'receipt',
    order: 15,
    accept: 'application/pdf',
    multiFile: true,
    layout: 'standard',
    artifactKind: 'pdf',
    orderSensitive: true,
    keywords: ['发票', '报销', '票据', 'invoice', '拼A4'],
    fields: [
      {
        type: 'select',
        key: 'sheetSize',
        labelKey: 'opt.invoice.sheet',
        default: 'a4',
        row: 'i1',
        options: [
          { value: 'a4', labelKey: 'opt.pageSize.a4' },
          { value: 'a3', labelKey: 'opt.pageSize.a3' },
          { value: 'letter', labelKey: 'opt.pageSize.letter' },
        ],
      },
      {
        type: 'select',
        key: 'perSheet',
        labelKey: 'opt.invoice.perSheet',
        default: 'auto',
        row: 'i1',
        options: [
          { value: 'auto', labelKey: 'opt.invoice.auto' },
          { value: 1, labelKey: 'opt.invoice.one' },
          { value: 2, labelKey: 'opt.invoice.two' },
          { value: 4, labelKey: 'opt.invoice.four' },
          { value: 6, labelKey: 'opt.invoice.six' },
        ],
      },
      {
        type: 'boolean',
        key: 'autoCrop',
        labelKey: 'opt.invoice.autoCrop',
        descriptionKey: 'opt.invoice.autoCrop.hint',
        default: true,
      },
      {
        type: 'select',
        key: 'orientation',
        labelKey: 'opt.orientation',
        default: 'auto',
        row: 'i2',
        options: [
          { value: 'auto', labelKey: 'opt.orientation.auto' },
          { value: 'portrait', labelKey: 'opt.orientation.portrait' },
          { value: 'landscape', labelKey: 'opt.orientation.landscape' },
        ],
      },
      {
        type: 'select',
        key: 'order',
        labelKey: 'opt.nup.order',
        default: 'horizontal',
        row: 'i2',
        options: [
          { value: 'horizontal', labelKey: 'opt.nup.orderHorizontal' },
          { value: 'vertical', labelKey: 'opt.nup.orderVertical' },
        ],
      },
      { type: 'number', key: 'gap', labelKey: 'opt.nup.gap', default: 6, min: 0, max: 40, suffixKey: 'unit.mm', displayUnit: 'mm', row: 'i3' },
      { type: 'number', key: 'margin', labelKey: 'opt.margin', default: 12, min: 0, max: 60, suffixKey: 'unit.mm', displayUnit: 'mm', row: 'i3' },
      { type: 'boolean', key: 'border', labelKey: 'opt.nup.border', default: false, section: 'advanced' },
      { type: 'boolean', key: 'sortByName', labelKey: 'opt.invoice.sort', default: true, section: 'advanced' },
      { type: 'boolean', key: 'skipDuplicates', labelKey: 'opt.invoice.dedupe', descriptionKey: 'opt.invoice.dedupe.hint', default: true, section: 'advanced' },
    ],
  },
  {
    id: 'pdf-to-word',
    nameKey: 'tool.pdfToWord.name',
    descKey: 'tool.pdfToWord.desc',
    category: 'convert',
    icon: 'word',
    order: 120,
    accept: 'application/pdf',
    multiFile: true,
    layout: 'standard',
    artifactKind: 'docx',
    keywords: ['word', 'docx', '转word'],
    fields: [IMAGES_FIELD(), PAGE_BREAK_FIELD],
  },
  {
    id: 'pdf-to-excel',
    nameKey: 'tool.pdfToExcel.name',
    descKey: 'tool.pdfToExcel.desc',
    category: 'convert',
    icon: 'excel',
    order: 121,
    accept: 'application/pdf',
    multiFile: true,
    layout: 'standard',
    artifactKind: 'xlsx',
    keywords: ['excel', 'xlsx', '表格', '转excel'],
    fields: [
      {
        type: 'boolean',
        key: 'sheetPerPage',
        labelKey: 'opt.convert.sheetPerPage',
        default: true,
      },
      {
        type: 'number',
        key: 'columnGap',
        labelKey: 'opt.convert.columnGap',
        descriptionKey: 'opt.convert.columnGap.hint',
        default: 8,
        min: 2,
        max: 60,
        suffixKey: 'unit.mm',
        displayUnit: 'mm',
        section: 'advanced',
      },
    ],
  },
  {
    id: 'pdf-to-ppt',
    nameKey: 'tool.pdfToPpt.name',
    descKey: 'tool.pdfToPpt.desc',
    category: 'convert',
    icon: 'ppt',
    order: 122,
    accept: 'application/pdf',
    multiFile: true,
    layout: 'standard',
    artifactKind: 'pptx',
    keywords: ['ppt', 'pptx', '幻灯片', '演示'],
    fields: [
      { type: 'boolean', key: 'textLayer', labelKey: 'opt.convert.textLayer', default: true },
      DPI_FIELD,
    ],
  },
  {
    id: 'pdf-to-markdown',
    nameKey: 'tool.pdfToMarkdown.name',
    descKey: 'tool.pdfToMarkdown.desc',
    category: 'convert',
    icon: 'markdown',
    order: 130,
    accept: 'application/pdf',
    multiFile: true,
    layout: 'standard',
    artifactKind: 'md',
    keywords: ['markdown', 'md', '转 md'],
    fields: [IMAGES_FIELD(), PAGE_BREAK_FIELD],
  },
  {
    id: 'pdf-to-html',
    nameKey: 'tool.pdfToHtml.name',
    descKey: 'tool.pdfToHtml.desc',
    category: 'convert',
    icon: 'globe',
    order: 131,
    accept: 'application/pdf',
    multiFile: true,
    layout: 'standard',
    artifactKind: 'html',
    keywords: ['html', '网页'],
    fields: [
      { type: 'boolean', key: 'embedImages', labelKey: 'opt.convert.embedImages', default: true },
      DPI_FIELD,
    ],
  },
  {
    id: 'pdf-to-csv',
    nameKey: 'tool.pdfToCsv.name',
    descKey: 'tool.pdfToCsv.desc',
    category: 'convert',
    icon: 'table',
    order: 132,
    accept: 'application/pdf',
    multiFile: true,
    layout: 'standard',
    artifactKind: 'csv',
    keywords: ['csv', '表格', '逗号'],
    fields: [
      {
        type: 'select',
        key: 'delimiter',
        labelKey: 'opt.convert.delimiter',
        default: 'comma',
        row: 'a',
        options: [
          { value: 'comma', labelKey: 'opt.convert.comma' },
          { value: 'semicolon', labelKey: 'opt.convert.semicolon' },
          { value: 'tab', labelKey: 'opt.convert.tab' },
        ],
      },
      {
        type: 'number',
        key: 'columnGap',
        labelKey: 'opt.convert.columnGap',
        default: 8,
        min: 2,
        max: 60,
        suffixKey: 'unit.mm',
        displayUnit: 'mm',
        row: 'a',
      },
    ],
  },
  {
    id: 'pdf-to-rtf',
    nameKey: 'tool.pdfToRtf.name',
    descKey: 'tool.pdfToRtf.desc',
    category: 'convert',
    icon: 'file-text',
    order: 133,
    accept: 'application/pdf',
    multiFile: true,
    layout: 'standard',
    artifactKind: 'rtf',
    keywords: ['rtf', 'write', '富文本'],
    fields: [PAGE_BREAK_FIELD],
  },
  {
    id: 'pdf-to-epub',
    nameKey: 'tool.pdfToEpub.name',
    descKey: 'tool.pdfToEpub.desc',
    category: 'convert',
    icon: 'book',
    order: 134,
    accept: 'application/pdf',
    multiFile: true,
    layout: 'standard',
    artifactKind: 'epub',
    keywords: ['epub', '电子书', '阅读'],
    fields: [
      {
        type: 'select',
        key: 'chapterBy',
        labelKey: 'opt.convert.chapterBy',
        default: 'heading',
        row: 'a',
        options: [
          { value: 'heading', labelKey: 'opt.convert.chapterByHeading' },
          { value: 'page', labelKey: 'opt.convert.chapterByPage' },
        ],
      },
      IMAGES_FIELD(),
    ],
  },
  {
    id: 'pdf-to-ofd',
    nameKey: 'tool.pdfToOfd.name',
    descKey: 'tool.pdfToOfd.desc',
    category: 'convert',
    icon: 'scan',
    order: 135,
    accept: 'application/pdf',
    multiFile: true,
    layout: 'standard',
    artifactKind: 'ofd',
    keywords: ['ofd', '国标', '版式', 'GB/T 33190'],
    fields: [
      {
        type: 'select',
        key: 'mode',
        labelKey: 'opt.ofd.mode',
        default: 'text',
        row: 'a',
        options: [
          { value: 'text', labelKey: 'opt.ofd.modeText' },
          { value: 'image', labelKey: 'opt.ofd.modeImage' },
        ],
      },
      DPI_FIELD,
    ],
  },
  {
    id: 'word-to-pdf',
    nameKey: 'tool.wordToPdf.name',
    descKey: 'tool.wordToPdf.desc',
    category: 'convert',
    icon: 'word',
    order: 140,
    accept: DOCX_MIME,
    multiFile: true,
    layout: 'standard',
    artifactKind: 'pdf',
    keywords: ['word', 'docx', '转 pdf'],
    fields: [
      {
        type: 'select',
        key: 'pageSize',
        labelKey: 'opt.pageSize',
        default: 'a4',
        row: 'a',
        options: [
          { value: 'a4', labelKey: 'opt.pageSize.a4' },
          { value: 'letter', labelKey: 'opt.pageSize.letter' },
          { value: 'a5', labelKey: 'opt.pageSize.a5' },
        ],
      },
      { type: 'number', key: 'margin', labelKey: 'opt.margin', default: 56, min: 0, max: 120, suffixKey: 'unit.mm', displayUnit: 'mm', row: 'a' },
    ],
  },
  { id: 'doc-to-docx', nameKey: 'tool.docToDocx.name', descKey: 'tool.docToDocx.desc', category: 'convert', icon: 'word', order: 135, accept: DOC_MIME, multiFile: true, layout: 'standard', artifactKind: 'docx', keywords: ['doc', 'docx', 'word', '旧版 word'], fields: [] },
  { id: 'docx-to-doc', nameKey: 'tool.docxToDoc.name', descKey: 'tool.docxToDoc.desc', category: 'convert', icon: 'word', order: 136, accept: `${DOCX_MIME},.docx`, multiFile: true, layout: 'standard', artifactKind: 'doc', keywords: ['docx', 'doc', 'word'], fields: [] },
  { id: 'xls-to-xlsx', nameKey: 'tool.xlsToXlsx.name', descKey: 'tool.xlsToXlsx.desc', category: 'convert', icon: 'excel', order: 137, accept: XLS_MIME, multiFile: true, layout: 'standard', artifactKind: 'xlsx', keywords: ['xls', 'xlsx', 'excel', '旧版表格'], fields: [] },
  { id: 'xlsx-to-xls', nameKey: 'tool.xlsxToXls.name', descKey: 'tool.xlsxToXls.desc', category: 'convert', icon: 'excel', order: 138, accept: `${XLSX_MIME},.xlsx`, multiFile: true, layout: 'standard', artifactKind: 'xls', keywords: ['xlsx', 'xls', 'excel'], fields: [] },
  { id: 'ppt-to-pptx', nameKey: 'tool.pptToPptx.name', descKey: 'tool.pptToPptx.desc', category: 'convert', icon: 'ppt', order: 139, accept: PPT_MIME, multiFile: true, layout: 'standard', artifactKind: 'pptx', keywords: ['ppt', 'pptx', 'powerpoint', '旧版演示文稿'], fields: [] },
  { id: 'pptx-to-ppt', nameKey: 'tool.pptxToPpt.name', descKey: 'tool.pptxToPpt.desc', category: 'convert', icon: 'ppt', order: 140, accept: `${PPTX_MIME},.pptx`, multiFile: true, layout: 'standard', artifactKind: 'ppt', keywords: ['pptx', 'ppt', 'powerpoint'], fields: [] },
  {
    id: 'excel-to-pdf',
    nameKey: 'tool.excelToPdf.name',
    descKey: 'tool.excelToPdf.desc',
    category: 'convert',
    icon: 'excel',
    order: 141,
    accept: XLSX_MIME,
    multiFile: true,
    layout: 'standard',
    artifactKind: 'pdf',
    keywords: ['excel', 'xlsx', '工作表', '转 pdf'],
    fields: [
      {
        type: 'select',
        key: 'pageSize',
        labelKey: 'opt.pageSize',
        default: 'a4',
        row: 'a',
        options: [
          { value: 'a4', labelKey: 'opt.pageSize.a4' },
          { value: 'a3', labelKey: 'opt.pageSize.a3' },
          { value: 'letter', labelKey: 'opt.pageSize.letter' },
        ],
      },
      {
        type: 'select',
        key: 'orientation',
        labelKey: 'opt.orientation',
        default: 'auto',
        row: 'a',
        options: [
          { value: 'auto', labelKey: 'opt.orientation.auto' },
          { value: 'portrait', labelKey: 'opt.orientation.portrait' },
          { value: 'landscape', labelKey: 'opt.orientation.landscape' },
        ],
      },
      { type: 'boolean', key: 'repeatHeader', labelKey: 'opt.convert.repeatHeader', default: true },
    ],
  },
  {
    id: 'ppt-to-pdf',
    nameKey: 'tool.pptToPdf.name',
    descKey: 'tool.pptToPdf.desc',
    category: 'convert',
    icon: 'ppt',
    order: 142,
    accept: PPTX_MIME,
    multiFile: true,
    layout: 'standard',
    artifactKind: 'pdf',
    keywords: ['ppt', 'pptx', '幻灯片', '转 pdf'],
    fields: [
      {
        type: 'select',
        key: 'pageSize',
        labelKey: 'opt.convert.slideSize',
        default: 'slide',
        row: 'a',
        options: [
          { value: 'slide', labelKey: 'opt.convert.slideKeep' },
          { value: 'a4', labelKey: 'opt.pageSize.a4' },
        ],
      },
    ],
  },
  {
    id: 'ofd-to-pdf',
    nameKey: 'tool.ofdToPdf.name',
    descKey: 'tool.ofdToPdf.desc',
    category: 'convert',
    icon: 'scan',
    order: 143,
    accept: '.ofd',
    multiFile: true,
    layout: 'standard',
    artifactKind: 'pdf',
    keywords: ['ofd', '国标', '转 pdf'],
    fields: [PAGES_FIELD],
  },
  {
    id: 'markdown-to-pdf',
    nameKey: 'tool.markdownToPdf.name',
    descKey: 'tool.markdownToPdf.desc',
    category: 'convert',
    icon: 'markdown',
    order: 150,
    accept: 'text/markdown',
    multiFile: true,
    layout: 'standard',
    artifactKind: 'pdf',
    keywords: ['markdown', 'md', '转 pdf'],
    fields: [
      {
        type: 'select',
        key: 'pageSize',
        labelKey: 'opt.pageSize',
        default: 'a4',
        row: 'a',
        options: [
          { value: 'a4', labelKey: 'opt.pageSize.a4' },
          { value: 'letter', labelKey: 'opt.pageSize.letter' },
        ],
      },
      { type: 'number', key: 'margin', labelKey: 'opt.margin', default: 56, min: 0, max: 120, suffixKey: 'unit.mm', displayUnit: 'mm', row: 'a' },
      { type: 'number', key: 'fontSize', labelKey: 'opt.convert.fontSize', default: 11, min: 8, max: 18, suffixKey: 'unit.pt' },
    ],
  },
  {
    id: 'image-compress', nameKey: 'tool.imageCompress.name', descKey: 'tool.imageCompress.desc', category: 'convert',
    icon: 'compress', order: 200, accept: IMAGE_ACCEPT, multiFile: true, layout: 'standard', artifactKind: 'image',
    keywords: ['图片压缩', 'image compression', '压缩图片'], fields: imageFields('compress'),
  },
  {
    id: 'image-resize', nameKey: 'tool.imageResize.name', descKey: 'tool.imageResize.desc', category: 'edit',
    icon: 'maximize', order: 210, accept: IMAGE_ACCEPT, multiFile: true, layout: 'standard', artifactKind: 'image',
    keywords: ['图片尺寸', '缩放图片', 'resize image'], fields: imageFields('resize'),
  },
  {
    id: 'image-crop', nameKey: 'tool.imageCrop.name', descKey: 'tool.imageCrop.desc', category: 'edit',
    icon: 'crop', order: 220, accept: IMAGE_ACCEPT, multiFile: true, layout: 'standard', artifactKind: 'image',
    keywords: ['裁剪图片', 'crop image', '比例裁切'], fields: imageFields('crop'),
  },
  {
    id: 'image-rotate', nameKey: 'tool.imageRotate.name', descKey: 'tool.imageRotate.desc', category: 'edit',
    icon: 'rotate-cw', order: 230, accept: IMAGE_ACCEPT, multiFile: true, layout: 'standard', artifactKind: 'image',
    keywords: ['翻转图片', '旋转图片', 'rotate image'], fields: imageFields('rotate'),
  },
  {
    id: 'image-convert', nameKey: 'tool.imageConvert.name', descKey: 'tool.imageConvert.desc', category: 'convert',
    icon: 'images', order: 240, accept: IMAGE_ACCEPT, multiFile: true, layout: 'standard', artifactKind: 'image',
    keywords: ['格式转换', 'jpg', 'png', 'webp', 'tiff'], fields: imageFields('convert'),
  },
  {
    id: 'image-info', nameKey: 'tool.imageInfo.name', descKey: 'tool.imageInfo.desc', category: 'metadata',
    icon: 'info', order: 250, accept: IMAGE_ACCEPT, multiFile: true, layout: 'standard', artifactKind: 'json',
    keywords: ['图片信息', '尺寸', '分辨率', 'exif'], fields: [],
  },
  {
    id: 'image-cutout', nameKey: 'tool.imageCutout.name', descKey: 'tool.imageCutout.desc', category: 'edit',
    icon: 'eraser', order: 260, accept: PORTRAIT_IMAGE_ACCEPT, multiFile: false, layout: 'standard', artifactKind: 'image',
    keywords: ['抠图', '去除背景', '透明背景', 'background removal', 'cutout'], fields: imageCutoutFields,
  },
  {
    id: 'image-id-photo', nameKey: 'tool.idPhoto.name', descKey: 'tool.idPhoto.desc', category: 'edit',
    icon: 'id-card', order: 270, accept: PORTRAIT_IMAGE_ACCEPT, multiFile: false, layout: 'standard', artifactKind: 'image',
    keywords: ['证件照', '登记照', '一寸', '二寸', 'passport photo'], fields: idPhotoFields,
  },
  { id: 'image-metadata-clean', nameKey: 'tool.imageMetadataClean.name', descKey: 'tool.imageMetadataClean.desc', category: 'metadata', icon: 'shield', order: 280, accept: IMAGE_ACCEPT, multiFile: true, layout: 'standard', artifactKind: 'image', keywords: ['EXIF', 'GPS', '隐私', 'metadata'], fields: [] },
  { id: 'image-print', nameKey: 'tool.imagePrint.name', descKey: 'tool.imagePrint.desc', category: 'convert', icon: 'printer', order: 290, accept: IMAGE_ACCEPT, multiFile: true, layout: 'standard', artifactKind: 'image', keywords: ['打印', 'A4', '纸张', 'print'], fields: imagePrintFields },
  { id: 'image-watermark-clean', nameKey: 'tool.imageWatermarkClean.name', descKey: 'tool.imageWatermarkClean.desc', category: 'edit', icon: 'eraser', order: 300, accept: 'image/jpeg,image/png,image/webp', multiFile: false, layout: 'standard', artifactKind: 'image', keywords: ['去水印', '修复', 'watermark'], fields: [] },
];

const TOOL_WORKFLOW_BY_ID: Record<ToolId, ToolWorkflow> = {
  merge: 'page-management', split: 'page-management', organize: 'page-management', rotate: 'page-management',
  'extract-pages': 'page-management', 'delete-pages': 'page-management',
  resize: 'page-layout', crop: 'page-layout', margins: 'page-layout', nup: 'page-layout', 'invoice-merge': 'page-layout',
  watermark: 'annotation', 'page-numbers': 'annotation', 'header-footer': 'annotation',
  'pdf-to-images': 'conversion', 'images-to-pdf': 'conversion', 'pdf-to-word': 'conversion', 'pdf-to-excel': 'conversion',
  'pdf-to-ppt': 'conversion', 'pdf-to-markdown': 'conversion', 'pdf-to-html': 'conversion', 'pdf-to-csv': 'conversion',
  'pdf-to-rtf': 'conversion', 'pdf-to-epub': 'conversion', 'pdf-to-ofd': 'conversion', 'word-to-pdf': 'conversion', 'doc-to-docx': 'conversion', 'docx-to-doc': 'conversion', 'xls-to-xlsx': 'conversion', 'xlsx-to-xls': 'conversion', 'ppt-to-pptx': 'conversion', 'pptx-to-ppt': 'conversion',
  'excel-to-pdf': 'conversion', 'ppt-to-pdf': 'conversion', 'ofd-to-pdf': 'conversion', 'markdown-to-pdf': 'conversion',
  'extract-images': 'extraction', 'extract-text': 'extraction',
  compress: 'optimization', repair: 'optimization', 'remove-blank': 'optimization',
  'image-compress': 'image-processing', 'image-resize': 'image-processing', 'image-crop': 'image-processing',
  'image-rotate': 'image-processing', 'image-convert': 'image-processing', 'image-cutout': 'image-processing', 'image-id-photo': 'image-processing', 'image-metadata-clean': 'metadata', 'image-print': 'image-processing', 'image-watermark-clean': 'image-processing',
  metadata: 'metadata',
  'image-info': 'metadata',
};

const INPUT_FORMATS: Record<string, ToolFormat> = {
  'application/pdf': 'pdf', [DOCX_MIME]: 'docx', '.docx': 'docx', 'application/msword': 'doc', '.doc': 'doc', 'application/vnd.ms-excel': 'xls', '.xls': 'xls', [XLSX_MIME]: 'xlsx', '.xlsx': 'xlsx', 'application/vnd.ms-powerpoint': 'ppt', '.ppt': 'ppt', [PPTX_MIME]: 'pptx', '.pptx': 'pptx',
  '.ofd': 'ofd', 'image/*': 'image', 'image/jpeg': 'jpg', 'image/png': 'png', 'image/webp': 'webp',
  'image/tiff': 'tiff', 'text/markdown': 'md',
};

const IMAGE_OUTPUTS: Partial<Record<ToolId, ToolFormat[]>> = {
  'image-compress': ['jpg', 'png', 'webp', 'tiff'], 'image-resize': ['jpg', 'png', 'webp', 'tiff'],
  'image-crop': ['jpg', 'png', 'webp', 'tiff'], 'image-rotate': ['jpg', 'png', 'webp', 'tiff'],
  'image-convert': ['jpg', 'png', 'webp', 'tiff'],
  'image-cutout': ['png'], 'image-id-photo': ['jpg'], 'image-metadata-clean': ['image'], 'image-print': ['jpg'], 'image-watermark-clean': ['png'],
};

export const TOOL_LIST: ToolDescriptor[] = TOOL_DEFINITIONS.map((tool) => ({
  ...tool,
  workflow: TOOL_WORKFLOW_BY_ID[tool.id],
  inputFormats: (tool.accept.split(',').map((format) => INPUT_FORMATS[format.trim()]).filter(Boolean) as ToolFormat[]),
  outputFormats: IMAGE_OUTPUTS[tool.id] ?? [tool.artifactKind],
}));

export const TOOLS: Record<ToolId, ToolDescriptor> = TOOL_LIST.reduce(
  (acc, t) => {
    acc[t.id] = t;
    return acc;
  },
  {} as Record<ToolId, ToolDescriptor>,
);

export const CATEGORY_ORDER: ToolCategory[] = [
  'organize',
  'convert',
  'extract',
  'optimize',
  'edit',
  'metadata',
];

export function defaultOptions(id: ToolId): Record<string, string | number | boolean> {
  return fieldsOf(TOOLS[id].fields);
}
