import {
  AlertTriangle,
  ArrowDown,
  ArrowUp,
  Check,
  ChevronDown,
  ChevronRight,
  Clock,
  Combine,
  Copy,
  Crop,
  Download,
  Droplets,
  Eraser,
  FileCode2,
  FileImage,
  ContactRound,
  FileSpreadsheet,
  FileText,
  FolderOpen,
  Frame,
  Globe,
  Hash,
  Images,
  Info,
  Layers,
  LayoutGrid,
  ListChecks,
  Loader2,
  Maximize,
  Minimize2,
  Monitor,
  Moon,
  Palette,
  Printer,
  PanelLeft,
  Play,
  BookOpen,
  Plus,
  Presentation,
  ReceiptText,
  ScanText,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Save,
  Scissors,
  Settings,
  ShieldCheck,
  Search,
  Sun,
  Table,
  Trash2,
  Type,
  Wrench,
  X,
  type LucideIcon,
} from 'lucide-react';

const MAP: Record<string, LucideIcon> = {
  merge: Combine,
  compress: Minimize2,
  combine: Combine,
  scissors: Scissors,
  'layout-grid': LayoutGrid,
  'rotate-cw': RotateCw,
  copy: Copy,
  eraser: Eraser,
  droplets: Droplets,
  hash: Hash,
  info: Info,
  minimize: Minimize2,
  images: Images,
  'file-image': FileImage,
  'id-card': ContactRound,
  'file-text': FileText,
  maximize: Maximize,
  crop: Crop,
  frame: Frame,
  type: Type,
  wrench: Wrench,
  receipt: ReceiptText,
  word: FileText,
  excel: FileSpreadsheet,
  ppt: Presentation,
  markdown: FileCode2,
  table: Table,
  book: BookOpen,
  scan: ScanText,
  layers: Layers,
  queue: ListChecks,
  settings: Settings,
  search: Search,
  close: X,
  check: Check,
  warning: AlertTriangle,
  spinner: Loader2,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  folder: FolderOpen,
  download: Download,
  save: Save,
  play: Play,
  plus: Plus,
  trash: Trash2,
  up: ArrowUp,
  down: ArrowDown,
  reset: RotateCcw,
  refresh: RefreshCw,
  clock: Clock,
  sun: Sun,
  moon: Moon,
  monitor: Monitor,
  palette: Palette,
  sidebar: PanelLeft,
  shield: ShieldCheck,
  printer: Printer,
  globe: Globe,
  file: FileText,
};

export type IconName = keyof typeof MAP;

export function Icon({
  name,
  size = 16,
  className = '',
  strokeWidth = 1.75,
}: {
  name: string;
  size?: number;
  className?: string;
  strokeWidth?: number;
}) {
  const Component = MAP[name] ?? FileText;
  return <Component size={size} strokeWidth={strokeWidth} className={className} aria-hidden />;
}
